import { ArrowUpRight, Filter, Search, Sparkles } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";

export default function Bounties() {
  const [query, setQuery] = useState("");
  const bounties = trpc.klipflow.bounties.useQuery();
  const filtered = (bounties.data ?? []).filter((bounty) => bounty.title.toLowerCase().includes(query.toLowerCase()));

  return <div className="space-y-7"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="mb-2 flex items-center gap-2 text-[#FF4D00]"><Sparkles size={17} /><span className="text-xs font-semibold uppercase tracking-[0.15em]">Opportunity feed</span></div><h1 className="text-3xl font-semibold tracking-[-0.04em] text-white">Bounties</h1><p className="mt-2 max-w-xl text-sm text-white/40">Campaigns available to your authenticated creator workspace.</p></div><Link href="/flows"><Button className="h-8 bg-[#FF4D00] text-xs uppercase text-white hover:bg-[#E64500]">Start a flow <ArrowUpRight size={15} /></Button></Link></div><div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-white/25" size={16} /><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search bounties" className="h-8 border-[#262626] bg-[#171717] pl-9 text-sm text-white placeholder:text-white/25" /></div><Button variant="outline" className="h-8 border-[#262626] bg-[#171717] text-xs uppercase text-white/60 hover:bg-[#262626] hover:text-white"><Filter size={15} /> Filters</Button></div>{bounties.isLoading && <div className="border border-[#262626] bg-[#171717] p-10 text-center text-sm text-white/40">Loading live campaigns…</div>}{bounties.error && <div className="border border-red-500/30 bg-[#171717] p-10 text-center text-sm text-red-200">Campaign data is unavailable. Check the connected Supabase/Whop source.</div>}{!bounties.isLoading && !bounties.error && filtered.length === 0 && <div className="border border-dashed border-[#262626] bg-[#171717] p-10 text-center"><div className="text-sm text-white/60">No live bounties available</div><p className="mt-2 text-xs text-white/35">No campaign rows were returned for this workspace. KlipFlow will show them here after the data source is connected.</p></div>} {!bounties.isLoading && !bounties.error && filtered.length > 0 && <div className="overflow-x-auto border border-[#262626] bg-[#171717]"><table className="w-full min-w-[720px] text-left"><thead className="border-b border-[#262626] text-[10px] uppercase tracking-[0.13em] text-white/30"><tr><th className="px-5 py-3">Opportunity</th><th className="px-5 py-3">Reward</th><th className="px-5 py-3">Channels</th><th className="px-5 py-3">Eligibility</th><th className="px-5 py-3">Status</th></tr></thead><tbody>{filtered.map((bounty) => <tr key={bounty.id} className="border-b border-[#262626] last:border-0"><td className="px-5 py-4 text-sm text-white/85">{bounty.title}</td><td className="px-5 py-4 text-sm font-semibold text-[#FF4D00]">{bounty.reward}</td><td className="px-5 py-4 text-xs text-white/45">{bounty.platform}</td><td className="px-5 py-4 text-xs text-white/45">{bounty.eligibility}</td><td className="px-5 py-4 text-xs uppercase text-white/55">{bounty.status}</td></tr>)}</tbody></table></div>}</div>;
}
