import express from "express";
// @ts-expect-error dist/index.js is generated by the build step before Vercel bundles this entrypoint.
import { app } from "./dist/index.js";

void express;

export default app;
