import { AlertCircle, Bell, CheckCircle2, Instagram, Link2, Play, RefreshCw, Trash2, Video } from "lucide-react";
import { useState } from "react";
import { trpc } from "@/lib/trpc";

const platforms = [{ id: "tiktok" as const, label: "TikTok", icon: Play }, { id: "instagram" as const, label: "Instagram", icon: Instagram }, { id: "youtube" as const, label: "YouTube", icon: Video }, { id: "x" as const, label: "X", icon: Link2 }, { id: "telegram" as const, label: "Telegram", icon: Bell }];

function oauthMessage() { const params = new URLSearchParams(window.location.search); const provider = params.get("oauth"); if (!provider) return null; if (provider.endsWith("-success")) return `${provider.replace("-success", "")} is connected. You can now post and sync views.`; return params.get("message") || "That account could not be connected."; }

export default function Accounts() {
  const accounts = trpc.klipflow.accounts.list.useQuery();
  const health = trpc.klipflow.accounts.health.useQuery(undefined, { enabled: false });
  const status = trpc.klipflow.integrationStatus.useQuery();
  const [platform, setPlatform] = useState<(typeof platforms)[number]["id"] | null>(null);
  const [handle, setHandle] = useState("");
  const [healthChecked, setHealthChecked] = useState(false);
  const [tiktokResult, setTiktokResult] = useState<{ profileName: string; avatarUrl: string; checkedAt: string } | null>(null);
  const connect = trpc.klipflow.accounts.connect.useMutation({ onSuccess: () => { accounts.refetch(); setPlatform(null); setHandle(""); } });
  const remove = trpc.klipflow.accounts.remove.useMutation({ onSuccess: () => { accounts.refetch(); health.refetch(); setTiktokResult(null); } });
  const testTikTok = trpc.klipflow.accounts.testTikTok.useMutation({ onSuccess: (result) => { setTiktokResult(result); accounts.refetch(); }, onError: () => setTiktokResult(null) });
  const message = oauthMessage();
  const instagramManual = status.data?.instagramOAuth !== "configured";
  const oauthReady = platform === "youtube" || platform === "tiktok" || (platform === "instagram" && !instagramManual);
  const tiktokAccount = accounts.data?.find((account) => account.platform === "tiktok");
  const checkHealth = () => { setHealthChecked(true); health.refetch(); };

  return <div className="space-y-6">
    <div><p className="text-sm font-semibold text-[#FF4D00]">Your accounts</p><h1 className="mt-1 text-3xl font-black">Connected Accounts</h1><p className="mt-2 text-sm text-black/50">Connect places for auto-posting and personal Telegram alerts.</p></div>
    {message && <div className="rounded-2xl bg-[#FFF1EB] p-4 text-sm font-bold text-[#B63D00]">{message}</div>}
    <section className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div><h2 className="font-black">Connection health</h2><p className="mt-1 text-xs text-black/45">Verify tokens and account access without exposing credentials.</p></div><button onClick={checkHealth} disabled={health.isFetching} className="flex h-10 items-center gap-2 rounded-xl border border-black/10 px-3 text-xs font-extrabold">{health.isFetching ? <RefreshCw className="animate-spin" size={15} /> : <RefreshCw size={15} />} Check now</button></div>{healthChecked && <div className="mt-4 grid gap-2 sm:grid-cols-2">{(health.data ?? []).map((item) => <div key={item.platform} className="rounded-2xl border border-black/5 p-3"><div className="flex items-center justify-between"><span className="font-extrabold capitalize">{item.platform}</span>{item.status === "healthy" ? <CheckCircle2 className="text-green-600" size={17} /> : item.status === "needs_attention" ? <AlertCircle className="text-red-500" size={17} /> : <span className="text-[10px] font-black uppercase text-black/35">{item.status.replace("_", " ")}</span>}</div><p className="mt-1 truncate text-xs text-black/50">{item.handle ?? item.message}</p></div>)}</div>}</section>
    <div className="space-y-3">{(accounts.data ?? []).map((account) => <div key={account.id} className="flex items-center gap-3 rounded-3xl bg-white p-4"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-[#FFF1EB] text-[#FF4D00]"><Link2 size={20} /></div><div className="flex-1"><div className="font-extrabold capitalize">{account.platform}</div><div className="text-sm text-black/45">{account.platform === "telegram" ? "Chat" : "@"}{account.handle} · <span className="font-semibold text-green-700">{account.status === "active" ? "OAuth connected" : "Connected"}</span></div></div>{account.platform === "tiktok" && <button onClick={() => testTikTok.mutate()} disabled={testTikTok.isPending} className="flex items-center gap-1 rounded-xl border border-black/10 px-3 py-2 text-[11px] font-extrabold">{testTikTok.isPending ? <RefreshCw className="animate-spin" size={13} /> : <CheckCircle2 size={13} />} Test</button>}<button aria-label="Remove account" onClick={() => remove.mutate({ id: account.id })} className="rounded-full p-2 text-black/35 hover:bg-black/5"><Trash2 size={17} /></button></div>)}{accounts.data?.length === 0 && !accounts.isLoading && <div className="rounded-3xl bg-white p-6 text-sm text-black/50">No accounts connected yet.</div>}</div>
    {tiktokResult && <div className="flex items-center gap-3 rounded-2xl border border-green-200 bg-green-50 p-4 text-sm text-green-800"><CheckCircle2 size={18} /><div><p className="font-extrabold">TikTok connection is working</p><p>Connected profile: <strong>{tiktokResult.profileName}</strong></p></div>{tiktokResult.avatarUrl && <img src={tiktokResult.avatarUrl} alt="TikTok profile" className="ml-auto h-10 w-10 rounded-full" />}</div>}
    <section className="rounded-3xl bg-white p-5"><h2 className="font-black">Connect an account</h2><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3">{platforms.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => setPlatform(id)} className={`flex h-12 items-center justify-center gap-2 rounded-2xl border text-sm font-bold ${platform === id ? "border-[#FF4D00] bg-[#FFF1EB] text-[#FF4D00]" : "border-black/10"}`}><Icon size={17} /> {label}</button>)}</div>{platform && <div className="mt-4">{platform === "instagram" && instagramManual ? <div className="space-y-3"><div className="rounded-2xl bg-[#FFF1EB] p-4 text-sm font-bold text-[#B63D00]">Instagram OAuth is optional — manual upload is ready</div><div className="rounded-2xl border border-black/5 p-4 text-sm leading-6 text-black/60"><h3 className="font-black text-black">How to post an Instagram clip manually</h3><ol className="mt-2 list-decimal space-y-1 pl-5"><li>Open <strong>My Clips</strong> and download the finished clip.</li><li>Open Instagram and create a Reel from the downloaded video.</li><li>Copy the published Reel URL.</li><li>Use the clip’s <strong>Submit post URL</strong> action to track it.</li></ol></div></div> : oauthReady ? <><p className="text-sm text-black/55">You will be sent to {platform === "youtube" ? "Google" : platform === "tiktok" ? "TikTok" : "Meta"} to approve account access.</p><a href={`/api/oauth/${platform}/start`} className="mt-3 flex h-12 w-full items-center justify-center rounded-2xl bg-[#FF4D00] text-sm font-extrabold text-white">Connect {platform} with OAuth</a>{platform === "tiktok" && <p className="mt-2 text-xs text-black/40">After connecting, use Test beside the account to verify the OAuth token and display the creator profile name.</p>}<p className="mt-2 text-xs text-black/40">TikTok requires an approved Login Kit app. YouTube requires a channel; Instagram requires a professional account.</p></> : <><input value={handle} onChange={(e) => setHandle(e.target.value)} placeholder={platform === "telegram" ? "Your Telegram chat ID" : `Your ${platform} username`} className="h-12 w-full rounded-2xl border border-black/10 bg-[#F7F7F5] px-4 text-sm outline-none focus:border-[#FF4D00]" /><button disabled={!handle.trim() || connect.isPending} onClick={() => connect.mutate({ platform, handle })} className="mt-3 h-12 w-full rounded-2xl bg-[#FF4D00] text-sm font-extrabold text-white">{connect.isPending ? "Saving…" : `Connect ${platform}`}</button></>}</div>}{connect.error && <p className="mt-3 text-xs text-red-600">{connect.error.message}</p>}{testTikTok.error && <p className="mt-3 text-xs text-red-600">TikTok test failed: {testTikTok.error.message}</p>}</section>
  </div>;
}
