import { Activity, CalendarClock, CheckCircle2, CircleDashed, ExternalLink, Send, Video } from "lucide-react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";

const label = (value: unknown) => String(value || "Not scheduled").replaceAll("_", " ");

export default function Dashboard() {
  const clips = trpc.klipflow.clips.list.useQuery(undefined, { refetchInterval: 60_000 });
  const health = trpc.klipflow.accounts.health.useQuery(undefined, { refetchInterval: 300_000 });
  const rows = clips.data ?? [];
  const posted = rows.filter((clip) => Array.isArray(clip.submissions) && clip.submissions[0]?.post_url).length;
  const pending = rows.length - posted;
  const attention = (health.data ?? []).filter((item) => item.status === "needs_attention").length;
  return <div className="space-y-6">
    <div className="flex items-end justify-between gap-3"><div><p className="text-sm font-semibold text-[#FF4D00]">Command center</p><h1 className="mt-1 text-3xl font-black">Content Dashboard</h1><p className="mt-2 text-sm text-black/50">Every generated clip, post status, platform connection, and posting deadline in one view.</p></div><Link href="/new-project"><button className="h-10 rounded-2xl bg-[#FF4D00] px-4 text-xs font-extrabold text-white">New project</button></Link></div>
    <div className="grid grid-cols-3 gap-2"><div className="rounded-2xl bg-white p-4"><Video className="text-[#FF4D00]" size={18} /><p className="mt-3 text-2xl font-black">{rows.length}</p><p className="text-xs text-black/45">Generated clips</p></div><div className="rounded-2xl bg-white p-4"><Send className="text-green-600" size={18} /><p className="mt-3 text-2xl font-black">{posted}</p><p className="text-xs text-black/45">Posted</p></div><div className="rounded-2xl bg-white p-4"><CircleDashed className="text-amber-500" size={18} /><p className="mt-3 text-2xl font-black">{pending}</p><p className="text-xs text-black/45">Awaiting post</p></div></div>
    {attention > 0 && <Link href="/accounts" className="flex items-center gap-3 rounded-2xl bg-red-50 p-4 text-sm font-bold text-red-700"><Activity size={18} /> {attention} connection{attention === 1 ? "" : "s"} need authorization. Review Connected Accounts.</Link>}
    <section className="rounded-3xl bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="font-black">Platform health</h2><p className="mt-1 text-xs text-black/45">Last checks run automatically every five minutes while this dashboard is open.</p></div><Link href="/accounts" className="text-xs font-extrabold text-[#FF4D00]">Manage accounts</Link></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{(health.data ?? []).map((item) => <div key={item.platform} className="flex items-center justify-between rounded-2xl border border-black/5 p-3"><div><p className="font-extrabold capitalize">{item.platform}</p><p className="text-xs text-black/45">{item.handle ?? item.message}</p></div>{item.status === "healthy" ? <CheckCircle2 className="text-green-600" size={18} /> : <span className="text-[10px] font-black uppercase text-black/40">{label(item.status)}</span>}</div>)}</div></section>
    <section className="space-y-3"><div className="flex items-center justify-between"><h2 className="font-black">All clips and posting schedules</h2><Link href="/clips" className="text-xs font-extrabold text-[#FF4D00]">Open clips</Link></div>{rows.length === 0 && <div className="rounded-3xl bg-white p-8 text-center text-sm text-black/45">Generate your first clips to see them here.</div>}{rows.map((clip) => { const submission = Array.isArray(clip.submissions) ? clip.submissions[0] : null; const isPosted = Boolean(submission?.post_url); return <article key={clip.id} className="flex items-center gap-3 rounded-2xl bg-white p-3 shadow-sm"><div className="flex h-14 w-20 items-center justify-center overflow-hidden rounded-xl bg-[#252525] text-white/40">{clip.clip_url ? <video src={clip.clip_url} className="h-full w-full object-cover" /> : <Video size={18} />}</div><div className="min-w-0 flex-1"><p className="truncate font-extrabold">{clip.title || "Untitled clip"}</p><p className="mt-1 text-xs capitalize text-black/45">{clip.projects?.[0]?.title || "Project"} · {isPosted ? `${submission?.platform} · ${label(submission?.status || "posted")}` : "Not posted"}</p><div className="mt-2 flex items-center gap-1 text-[11px] font-bold text-black/45"><CalendarClock size={13} /> {submission?.posted_at ? `Posted ${new Date(submission.posted_at).toLocaleString()}` : "Schedule: ready to post"}</div></div>{isPosted ? <a href={submission?.post_url ?? undefined} target="_blank" rel="noreferrer" className="rounded-full p-2 text-[#FF4D00]" aria-label="Open post"><ExternalLink size={17} /></a> : <Link href="/clips" className="rounded-xl bg-[#FFF1EB] px-3 py-2 text-[11px] font-extrabold text-[#B63D00]">Post</Link>}</article>; })}</section>
  </div>;
}
