import { BarChart3, Calculator, Eye, Info, Settings as SettingsIcon } from "lucide-react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";

export default function Earnings() {
  const earnings = trpc.klipflow.earnings.useQuery();
  if (earnings.isLoading) return <div className="rounded-3xl bg-white p-8 text-center text-sm text-black/45">Loading your estimate…</div>;
  if (earnings.error) return <div className="rounded-3xl bg-white p-8 text-center text-sm text-black/50">Your estimate is not available yet. Try again soon.</div>;
  const data = earnings.data;
  return <div className="space-y-6"><div><p className="text-sm font-semibold text-[#FF4D00]">Your estimate</p><h1 className="mt-1 text-3xl font-black">Earnings</h1><p className="mt-2 text-sm text-black/50">Estimate what your Whop Content Rewards posts may earn.</p></div><section className="rounded-3xl bg-[#FF4D00] p-6 text-white"><div className="flex items-center gap-2 text-sm font-semibold text-white/80"><Calculator size={18} /> Estimated earnings</div><div className="mt-3 text-4xl font-black">${Number(data?.estimatedEarnings ?? 0).toFixed(2)}</div><p className="mt-1 text-sm text-white/75">Based on your rates and tracked views</p></section><div className="grid grid-cols-3 gap-2"><div className="rounded-2xl bg-white p-3 text-center"><Eye className="mx-auto text-[#FF4D00]" size={18} /><div className="mt-2 text-lg font-black">{data?.totalViews ?? 0}</div><div className="text-xs text-black/45">Views</div></div><div className="rounded-2xl bg-white p-3 text-center"><BarChart3 className="mx-auto text-[#FF4D00]" size={18} /><div className="mt-2 text-lg font-black">{data?.submittedClips ?? 0}</div><div className="text-xs text-black/45">Submitted</div></div><div className="rounded-2xl bg-white p-3 text-center"><SettingsIcon className="mx-auto text-[#FF4D00]" size={18} /><div className="mt-2 text-lg font-black">{Object.values(data?.rates ?? {}).filter(Boolean).length}</div><div className="text-xs text-black/45">Rates set</div></div></div><section className="rounded-3xl bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-extrabold">Your clips</h2><Link href="/settings" className="text-sm font-bold text-[#FF4D00]">Edit rates</Link></div>{data?.history.length ? <div className="mt-4 space-y-3">{data.history.map((row) => <div key={row.id} className="flex items-center justify-between border-b border-black/5 pb-3 last:border-0"><div><div className="text-sm font-bold">{row.platform ?? "Platform not set"}</div><div className="text-xs text-black/40">{row.views ?? 0} views · {row.whop_submission_status === "submitted" ? "Submitted to Whop" : "Not submitted"}</div></div><div className="font-black text-[#FF4D00]">${Number(row.estimated ?? 0).toFixed(2)}</div></div>)}</div> : <div className="mt-4 rounded-2xl bg-[#F7F7F5] p-5 text-center text-sm text-black/45">Your estimate will appear after your clips start getting views.</div>}</section><div className="flex gap-3 rounded-2xl bg-white p-4 text-sm text-black/50"><Info className="shrink-0 text-[#FF4D00]" size={18} /><span>This is an estimate only. KlipFlow does not pay you or control Whop payouts. Set the rates shown in your own Whop campaigns.</span></div></div>;
}
