import { Bell, Save } from "lucide-react";
import { useEffect, useState } from "react";
import { trpc } from "@/lib/trpc";

const platforms = [{ key: "tiktokRate", label: "TikTok" }, { key: "instagramRate", label: "Instagram" }, { key: "youtubeRate", label: "YouTube" }, { key: "xRate", label: "X" }] as const;
type RateKey = typeof platforms[number]["key"];
export default function Settings() {
  const settings = trpc.klipflow.settings.get.useQuery(); const save = trpc.klipflow.settings.save.useMutation(); const [rates, setRates] = useState<Record<RateKey, string>>({ tiktokRate: "", instagramRate: "", youtubeRate: "", xRate: "" }); const [telegramChatId, setTelegramChatId] = useState(""); const [telegramEnabled, setTelegramEnabled] = useState(false); const [milestone, setMilestone] = useState("10000");
  useEffect(() => { if (!settings.data) return; setRates({ tiktokRate: settings.data.tiktok_rate?.toString() ?? "", instagramRate: settings.data.instagram_rate?.toString() ?? "", youtubeRate: settings.data.youtube_rate?.toString() ?? "", xRate: settings.data.x_rate?.toString() ?? "" }); setTelegramChatId(settings.data.telegram_chat_id ?? ""); setTelegramEnabled(settings.data.telegram_enabled); setMilestone(settings.data.telegram_milestone.toString()); }, [settings.data]);
  const submit = () => save.mutate({ ...Object.fromEntries(platforms.map(({ key }) => [key, rates[key] ? Number(rates[key]) : null])) as Pick<Record<RateKey, number | null>, RateKey>, telegramChatId: telegramChatId || null, telegramEnabled, telegramMilestone: Number(milestone) || 10000 });
  return <div className="space-y-6"><div><p className="text-sm font-semibold text-[#FF4D00]">Your preferences</p><h1 className="mt-1 text-3xl font-black">My Settings</h1><p className="mt-2 text-sm text-black/50">Only you can see these rates and alerts.</p></div><section className="rounded-3xl bg-white p-5"><h2 className="font-black">My Whop rates</h2><p className="mt-1 text-sm text-black/45">Enter what each Whop Content Rewards campaign pays you per 1,000 views.</p><div className="mt-4 grid gap-3">{platforms.map(({ key, label }) => <label key={key} className="flex items-center justify-between gap-3 text-sm font-bold"><span>{label}</span><div className="flex items-center gap-2"><span className="text-black/40">$</span><input type="number" min="0" step="0.01" value={rates[key]} onChange={(e) => setRates({ ...rates, [key]: e.target.value })} placeholder="0.00" className="h-11 w-28 rounded-xl border border-black/10 bg-[#F7F7F5] px-3 outline-none focus:border-[#FF4D00]" /><span className="text-xs font-normal text-black/40">/ 1k</span></div></label>)}</div></section><section className="rounded-3xl bg-white p-5"><div className="flex items-center gap-2"><Bell className="text-[#FF4D00]" size={19} /><h2 className="font-black">Telegram alerts</h2></div><p className="mt-1 text-sm text-black/45">Get alerts about your projects, not new campaigns.</p><label className="mt-4 flex items-center justify-between rounded-2xl bg-[#F7F7F5] p-4 text-sm font-bold">Turn on alerts<input type="checkbox" checked={telegramEnabled} onChange={(e) => setTelegramEnabled(e.target.checked)} className="h-5 w-5 accent-[#FF4D00]" /></label><input value={telegramChatId} onChange={(e) => setTelegramChatId(e.target.value)} placeholder="Your Telegram chat ID" className="mt-3 h-11 w-full rounded-xl border border-black/10 bg-[#F7F7F5] px-3 text-sm outline-none focus:border-[#FF4D00]" /><label className="mt-3 block text-sm font-bold">View milestone<input type="number" min="100" value={milestone} onChange={(e) => setMilestone(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-black/10 bg-[#F7F7F5] px-3 text-sm outline-none focus:border-[#FF4D00]" /></label><p className="mt-3 text-xs text-black/40">Alerts cover: clip ready, auto-post success, and milestone views.</p></section><button onClick={submit} disabled={save.isPending} className="flex h-12 w-full items-center justify-center gap-2 rounded-2xl bg-[#FF4D00] text-sm font-extrabold text-white"><Save size={17} /> {save.isPending ? "Saving…" : "Save settings"}</button>{save.isSuccess && <p className="text-center text-sm font-bold text-green-700">Settings saved.</p>}{save.error && <p className="text-center text-sm text-red-600">{save.error.message}</p>}</div>;
}
