import { Bell, Instagram, Play, SkipForward, Video, X } from "lucide-react";
import { useState } from "react";
import { trpc } from "@/lib/trpc";

const options = [{ id: "tiktok" as const, name: "TikTok", icon: Play }, { id: "instagram" as const, name: "Instagram", icon: Instagram }, { id: "youtube" as const, name: "YouTube", icon: Video }, { id: "x" as const, name: "X", icon: X }, { id: "telegram" as const, name: "Telegram alerts", icon: Bell }];
type AccountPlatform = typeof options[number]["id"];
export default function Onboarding() {
  const accounts = trpc.klipflow.accounts.list.useQuery(); const connect = trpc.klipflow.accounts.connect.useMutation({ onSuccess: () => accounts.refetch() }); const [handleFor, setHandleFor] = useState<AccountPlatform | null>(null); const [handle, setHandle] = useState(""); const [skipped, setSkipped] = useState(() => localStorage.getItem("klipflow_onboarding_skipped") === "1");
  if (accounts.isLoading || accounts.data?.length || skipped) return null;
  const save = (platform: AccountPlatform) => { if (!handle.trim()) return; connect.mutate({ platform, handle: handle.trim() }, { onSuccess: () => { setHandle(""); setHandleFor(null); } }); };
  return <div className="fixed inset-0 z-[60] flex items-end justify-center bg-black/55 p-3 sm:items-center"><div className="max-h-[92vh] w-full max-w-md overflow-y-auto rounded-[2rem] bg-white p-5 shadow-xl"><div className="mx-auto h-1.5 w-12 rounded-full bg-black/10" /><div className="mt-5 overflow-hidden rounded-[1.5rem] bg-[#0A0A0A] p-5 text-center"><img src="/manus-storage/klipflow-orange-kf_0444aca3.webp" alt="KlipFlow" className="mx-auto h-20 w-20 rounded-2xl" /><h1 className="mt-4 text-2xl font-black text-white">Connect your accounts to auto-post</h1><p className="mt-2 text-sm leading-6 text-white/65">Connect social accounts for auto-posting and Telegram for personal alerts. You can do this later in Connected Accounts.</p></div><div className="mt-5 space-y-3">{options.map(({ id, name, icon: Icon }) => <div key={id}>{handleFor === id ? <div className="rounded-2xl bg-[#F7F7F5] p-3"><div className="flex items-center gap-2 text-sm font-bold"><Icon size={18} /> {name}</div><input autoFocus value={handle} onChange={(e) => setHandle(e.target.value)} placeholder={id === "telegram" ? "Your Telegram chat ID" : `Your ${name} username`} className="mt-3 h-11 w-full rounded-xl border border-black/10 bg-white px-3 text-sm outline-none focus:border-[#FF4D00]" /><button onClick={() => save(id)} disabled={!handle.trim() || connect.isPending} className="mt-2 h-10 w-full rounded-xl bg-[#FF4D00] text-sm font-bold text-white">{connect.isPending ? "Saving…" : `Connect ${name}`}</button></div> : <button onClick={() => setHandleFor(id)} className="flex h-14 w-full items-center gap-3 rounded-2xl border border-black/10 px-4 text-left font-bold hover:border-[#FF4D00]"><Icon size={21} /> Connect {name}<span className="ml-auto text-black/25">›</span></button>}</div>)}</div>{connect.error && <p className="mt-3 text-center text-xs text-red-600">We could not save that account. Please try again.</p>}<button onClick={() => { localStorage.setItem("klipflow_onboarding_skipped", "1"); setSkipped(true); }} className="mt-6 flex w-full items-center justify-center gap-2 text-sm font-semibold text-black/45 hover:text-black"><SkipForward size={16} /> Skip for now</button><p className="mt-2 text-center text-xs leading-5 text-black/40">You can connect accounts any time from the menu.</p></div></div>;
}
